#Requires -Version 5.1
<#
.SYNOPSIS
    Bootstrap mcpvectordb for native Windows 11 use with Claude Desktop (stdio transport).

.DESCRIPTION
    Checks prerequisites, installs Python dependencies, creates data directories,
    generates a .env file with Windows-appropriate paths, and prints the Claude Desktop
    config JSON block you need to paste into claude_desktop_config.json.

.NOTES
    Run from the mcpvectordb project root:
        .\scripts\setup-windows.ps1

    Requires: uv (https://docs.astral.sh/uv/), Python 3.11+, Claude Desktop for Windows.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Helpers ────────────────────────────────────────────────────────────────────

function Write-Step { param([string]$Message) Write-Host "`n>>> $Message" -ForegroundColor Cyan }
function Write-OK   { param([string]$Message) Write-Host "    OK  $Message" -ForegroundColor Green }
function Write-Warn { param([string]$Message) Write-Host "    WARN $Message" -ForegroundColor Yellow }
function Write-Fail { param([string]$Message) Write-Host "    FAIL $Message" -ForegroundColor Red; exit 1 }

# ── Step 1: Check uv ──────────────────────────────────────────────────────────

Write-Step "Checking for uv..."
if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
    Write-Host ""
    Write-Host "  uv is not installed or not on PATH." -ForegroundColor Red
    Write-Host "  Install it with:" -ForegroundColor Yellow
    Write-Host "      irm https://astral.sh/uv/install.ps1 | iex" -ForegroundColor White
    Write-Host "  Then open a new terminal and re-run this script." -ForegroundColor Yellow
    exit 1
}
$uvVersion = (uv --version) -replace "uv ", ""
Write-OK "uv $uvVersion found"

# ── Step 2: Ensure Python 3.13 is available ───────────────────────────────────
# onnxruntime (required by fastembed) does not yet publish wheels for Python 3.14+.
# We pin to 3.13 explicitly so uv never picks a newer system Python by accident.

Write-Step "Ensuring Python 3.13 is available via uv..."
$py313Ok = $false
try {
    $pyOutput = uv python list 2>&1
    if ($pyOutput -match "3\.13") {
        $py313Ok = $true
        Write-OK "Python 3.13 already available"
    }
} catch {}

if (-not $py313Ok) {
    Write-Host "    Installing Python 3.13 via uv (one-time download)..." -ForegroundColor Yellow
    uv python install 3.13
    if ($LASTEXITCODE -ne 0) { Write-Fail "Failed to install Python 3.13" }
    Write-OK "Python 3.13 installed"
}

# ── Step 3: Install Python dependencies ───────────────────────────────────────

Write-Step "Installing Python dependencies (uv sync --python 3.13)..."
uv sync --python 3.13
if ($LASTEXITCODE -ne 0) { Write-Fail "uv sync failed" }
Write-OK "Dependencies installed"

# ── Step 4: Download embedding model ──────────────────────────────────────────
# The model (~500 MB ONNX) is downloaded once to AppData\Local\mcpvectordb\models.
# Subsequent starts use the cached copy — no network access required at runtime.

Write-Step "Downloading embedding model (nomic-embed-text-v1.5, ~500 MB)..."
Write-Host "    This is a one-time download. Skip with Ctrl+C if already done." -ForegroundColor Yellow
uv run mcpvectordb-download-model
if ($LASTEXITCODE -ne 0) { Write-Warn "Model download failed — server will re-attempt on first run." }
else { Write-OK "Embedding model ready" }

# ── Step 5: Create data directories ───────────────────────────────────────────

Write-Step "Creating data directories..."

$DataDir = Join-Path $env:LOCALAPPDATA "mcpvectordb"
$LanceDir = Join-Path $DataDir "lancedb"
$ModelsDir = Join-Path $DataDir "models"

foreach ($Dir in @($LanceDir, $ModelsDir)) {
    if (-not (Test-Path $Dir)) {
        New-Item -ItemType Directory -Path $Dir -Force | Out-Null
        Write-OK "Created $Dir"
    } else {
        Write-OK "Already exists: $Dir"
    }
}

# ── Step 6: Generate .env (skip if it already exists) ─────────────────────────

Write-Step "Generating .env..."

$EnvFile = Join-Path $PSScriptRoot ".." ".env"
$EnvFile = [System.IO.Path]::GetFullPath($EnvFile)

if (Test-Path $EnvFile) {
    Write-Warn ".env already exists — skipping generation (delete it to regenerate)"
} else {
    $EnvContent = @"
# mcpvectordb — Windows 11 local configuration
# Generated by scripts\setup-windows.ps1
# Edit as needed; never commit this file.

MCP_TRANSPORT=stdio

LANCEDB_URI=$LanceDir
FASTEMBED_CACHE_PATH=$ModelsDir

LOG_LEVEL=INFO
# LOG_FILE=$DataDir\server.log
"@
    Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8
    Write-OK "Created .env at $EnvFile"
}

# ── Step 7: Print Claude Desktop config snippet ────────────────────────────────

Write-Step "Claude Desktop configuration"

# Resolve the project directory (parent of scripts/)
$ProjectDir = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))

# Claude Desktop config file location on Windows
$ClaudeConfig = Join-Path $env:APPDATA "Claude" "claude_desktop_config.json"

Write-Host ""
Write-Host "  Paste the following into:" -ForegroundColor Yellow
Write-Host "  $ClaudeConfig" -ForegroundColor White
Write-Host ""
Write-Host "  If the file already contains an 'mcpServers' key, add only the" -ForegroundColor Yellow
Write-Host "  'mcpvectordb' entry inside that existing object." -ForegroundColor Yellow
Write-Host ""

# Use forward slashes in the JSON for readability; Windows accepts both.
$ProjectJson  = $ProjectDir  -replace "\\", "\\"
$LanceDirJson = $LanceDir    -replace "\\", "\\"
$ModelsDirJson= $ModelsDir   -replace "\\", "\\"

Write-Host @"
{
  "mcpServers": {
    "mcpvectordb": {
      "command": "uv",
      "args": ["run", "--directory", "$ProjectJson", "mcpvectordb"],
      "env": {
        "MCP_TRANSPORT": "stdio",
        "LANCEDB_URI": "$LanceDirJson",
        "FASTEMBED_CACHE_PATH": "$ModelsDirJson",
        "LOG_LEVEL": "INFO"
      }
    }
  }
}
"@ -ForegroundColor White

# ── Step 8: Done ──────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "  Embedding model is pre-downloaded — server starts instantly." -ForegroundColor Green
Write-Host ""
Write-Host "Setup complete. Restart Claude Desktop to activate the server." -ForegroundColor Green
Write-Host ""
Write-Host "  Tip: To build a self-contained .exe (no Python needed on target machine):" -ForegroundColor Cyan
Write-Host "       .\scripts\build-windows.ps1" -ForegroundColor White
