#!/usr/bin/env bash
# Bootstrap mcpvectordb for native Linux use over stdio (Claude Desktop, Claude Code).
#
# Installs Python dependencies, pre-downloads the embedding model, creates the data
# directories, generates .env, and prints the MCP client config to paste.
# Linux counterpart of scripts/setup-windows.ps1.
#
# Usage (from anywhere):  ./scripts/setup-linux.sh
set -euo pipefail
# shellcheck source=scripts/_common-linux.sh
source "$(dirname "$0")/_common-linux.sh"

install_base

step "Generating .env..."
if [[ -f "$ENV_FILE" ]]; then
    warn ".env already exists — skipping generation (delete it to regenerate)"
else
    cat >"$ENV_FILE" <<EOF
# mcpvectordb — Linux local configuration
# Generated by scripts/setup-linux.sh
# Edit as needed; never commit this file.

MCP_TRANSPORT=stdio

LANCEDB_URI=$LANCE_DIR
FASTEMBED_CACHE_PATH=$MODELS_DIR

LOG_LEVEL=INFO
# LOG_FILE=$DATA_DIR/server.log
EOF
    ok "Created $ENV_FILE"
fi

step "MCP client configuration"
cat <<EOF

  Claude Desktop — paste into ${XDG_CONFIG_HOME:-$HOME/.config}/Claude/claude_desktop_config.json
  (if the file already has an "mcpServers" key, add only the "mcpvectordb" entry):

{
  "mcpServers": {
    "mcpvectordb": {
      "command": "$(command -v uv)",
      "args": ["run", "--directory", "$PROJECT_DIR", "mcpvectordb"],
      "env": {
        "MCP_TRANSPORT": "stdio",
        "LANCEDB_URI": "$LANCE_DIR",
        "FASTEMBED_CACHE_PATH": "$MODELS_DIR",
        "LOG_LEVEL": "INFO"
      }
    }
  }
}

  Claude Code — run once:

      claude mcp add mcpvectordb --scope user -- uv run --directory "$PROJECT_DIR" mcpvectordb

  The full path to uv is used above because desktop apps started from a launcher
  do not inherit your shell PATH (~/.local/bin is often missing).

Setup complete. Restart Claude Desktop to activate the server.
  Tip: to build a self-contained binary (no Python on the target): ./scripts/build-linux.sh
EOF
