#!/usr/bin/env bash
# Run mcpvectordb as a background systemd user service (streamable-http) so URL-based
# MCP clients such as ChatGPT can reach it, typically through `tailscale serve`.
# Linux counterpart of scripts/setup-chatgpt-windows.ps1: systemd replaces servy-cli,
# and a user service replaces the SYSTEM service, so no root is needed and the data
# stays in ~/.mcpvectordb.
#
# Usage:  ./scripts/setup-chatgpt-linux.sh
# Env overrides: MCP_PORT (default 8000, or MCP_PORT in .env), ALLOWED_HOSTS
# (default: this machine's Tailscale hostname, if tailscale is installed).
set -euo pipefail
# shellcheck source=scripts/_common-linux.sh
source "$(dirname "$0")/_common-linux.sh"

SERVICE=mcpvectordb-chatgpt
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT_FILE="$UNIT_DIR/$SERVICE.service"

step "Checking for systemd user session..."
command -v systemctl >/dev/null || fail "systemctl not found — this script needs systemd."
systemctl --user show-environment >/dev/null 2>&1 \
    || fail "No systemd user session. Log in normally (not via 'su'/'sudo') and re-run."
ok "systemd user session available"

install_base

# Transport settings live in the unit (they override .env), so an existing stdio .env
# for Claude Desktop can stay as it is. Data paths still come from .env or defaults.
if [[ -z "${MCP_PORT:-}" && -f "$ENV_FILE" ]]; then
    MCP_PORT="$(sed -n 's/^MCP_PORT[[:space:]]*=[[:space:]]*\([0-9]\+\).*/\1/p' "$ENV_FILE" | tail -1)"
fi
MCP_PORT="${MCP_PORT:-8000}"

# Stop our own previous install first so a re-run does not trip the port check.
if systemctl --user is-active --quiet "$SERVICE"; then
    warn "Service '$SERVICE' already running — stopping it for reinstall..."
    systemctl --user stop "$SERVICE"
fi

step "Checking port $MCP_PORT..."
if ss -Hltn "sport = :$MCP_PORT" | grep -q .; then
    ss -Hltnp "sport = :$MCP_PORT" || true
    fail "Port $MCP_PORT is already in use. Re-run with MCP_PORT=<free port>."
fi
ok "Port $MCP_PORT is free"

# The server binds 127.0.0.1, so FastMCP rejects any Host header other than
# localhost. tailscale serve forwards the tailnet hostname, which must be allowed.
if [[ -z "${ALLOWED_HOSTS:-}" ]] && command -v tailscale >/dev/null; then
    ALLOWED_HOSTS="$(tailscale status --json 2>/dev/null | uv run --directory "$PROJECT_DIR" \
        python -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))' \
        2>/dev/null || true)"
fi

step "Installing systemd user service '$SERVICE'..."
mkdir -p "$UNIT_DIR"
cat >"$UNIT_FILE" <<EOF
# Generated by scripts/setup-chatgpt-linux.sh — re-run the script to regenerate.
[Unit]
Description=mcpvectordb MCP server (streamable-http) for ChatGPT
After=network-online.target

[Service]
ExecStart="$(command -v uv)" run --directory "$PROJECT_DIR" mcpvectordb
Environment="MCP_TRANSPORT=streamable-http"
Environment="MCP_HOST=127.0.0.1"
Environment="MCP_PORT=$MCP_PORT"
${ALLOWED_HOSTS:+Environment=\"ALLOWED_HOSTS=$ALLOWED_HOSTS\"}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
ok "Wrote $UNIT_FILE"

systemctl --user daemon-reload
systemctl --user enable --now "$SERVICE" || warn "Service failed to start. Check: journalctl --user -u $SERVICE"
systemctl --user is-active --quiet "$SERVICE" && ok "Service started"

# Without lingering, user services stop at logout and do not start at boot.
if loginctl enable-linger "$USER" 2>/dev/null; then
    ok "Lingering enabled — service starts at boot"
else
    warn "Could not enable lingering; the service runs only while you are logged in."
    warn "Fix with: sudo loginctl enable-linger $USER"
fi

cat <<EOF

  Setup complete. The server listens on http://127.0.0.1:$MCP_PORT/mcp

  ChatGPT requires HTTPS. Expose the server over your tailnet with:

      tailscale serve --bg http://127.0.0.1:$MCP_PORT

  Then paste the resulting URL, with /mcp appended, into ChatGPT:
  Settings → Apps → Advanced settings → Developer mode

      https://${ALLOWED_HOSTS:-<your-tailscale-hostname>}/mcp
EOF
if [[ -z "${ALLOWED_HOSTS:-}" ]]; then
    cat <<EOF

  Tailscale hostname not detected. Re-run with it allowed, or requests are rejected:

      ALLOWED_HOSTS=<your-tailscale-hostname> ./scripts/setup-chatgpt-linux.sh
EOF
fi
cat <<EOF

  Open a new ChatGPT conversation and ask "List all libraries" to confirm.

  Logs:      journalctl --user -u $SERVICE -f
  Uninstall: ./scripts/uninstall-chatgpt-linux.sh
EOF
